// This file is generated by Slice Machine. Update with care!

import BigHighlightBlock from './BigHighlightBlock';
import BottomCarousel from './BottomCarousel';
import HomeHeroSlider from './HomeHeroSlider';
import HomeSectionFeatured from './HomeSectionFeatured';
import HomeSectionHighlighted from './HomeSectionHighlighted';
import IntroductionText from './IntroductionText';
import PageBanner from './PageBanner';
import PersonCardBlock from './PersonCardBlock';
import SponsorsList from './SponsorsList';
import SubscriptionBlock from './SubscriptionBlock';
import TitleDescriptionBlock from './TitleDescriptionBlock';

export {
	BigHighlightBlock,
	BottomCarousel,
	HomeHeroSlider,
	HomeSectionFeatured,
	HomeSectionHighlighted,
	IntroductionText,
	PageBanner,
	PersonCardBlock,
	SponsorsList,
	SubscriptionBlock,
	TitleDescriptionBlock,
};

export const components = {
	big_highlight_block: BigHighlightBlock,
	bottom_carousel: BottomCarousel,
	home_hero_slider: HomeHeroSlider,
	home_section_featured: HomeSectionFeatured,
	home_section_highlighted: HomeSectionHighlighted,
	introduction_text: IntroductionText,
	page_banner: PageBanner,
	person_card_block: PersonCardBlock,
	sponsors_list: SponsorsList,
	subscription_block: SubscriptionBlock,
	title_description_block: TitleDescriptionBlock,
};
